/**
 * Regenerates src/lib/server/languages/iso-data.generated.ts from the pinned
 * iso-639-3 package. Run with: npm run generate:language-data
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { iso6393 } from 'iso-639-3';

const OUTPUT_PATH = resolve('src/lib/server/languages/iso-data.generated.ts');

const mapping: Record<string, string> = {};

for (const entry of iso6393) {
	const canonical = entry.iso6391 ?? entry.iso6393;
	for (const key of [entry.iso6391, entry.iso6392B, entry.iso6392T, entry.iso6393]) {
		if (!key) continue;
		mapping[key.toLowerCase()] = canonical;
	}
}

const sorted = Object.fromEntries(
	Object.entries(mapping).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
);

const banner = [
	'// AUTO-GENERATED by scripts/generate-language-data.ts - do not edit by hand.',
	'// Source: iso-639-3@3.0.1 (ISO 639-3 data).',
	'// Regenerate with: npm run generate:language-data',
	'',
	'/** Maps every ISO 639-1/2B/2T/3 code (lower-case) to its canonical tag. */',
	'export const ISO_TO_CANONICAL: Readonly<Record<string, string>> = '
].join('\n');

mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
writeFileSync(OUTPUT_PATH, `${banner}${JSON.stringify(sorted, null, '\t')};\n`);
console.log(`Wrote ${Object.keys(sorted).length} ISO codes to ${OUTPUT_PATH}`);
